### ISSUE TITLE
Submit to CRAN

### ISSUE THREAD

**Issue by MurielleDelmotte** [ThinkR-open/gitlabr#102]
## Tech 

- [x] Passer en 2.1.0
- [x] Suivre les consignes dev_history + Prepare for CRAN: https://github.com/ThinkR-open/prepare-for-cran

**Comment by MurielleDelmotte** [comment]
rhub:

`on_windows` ✅ 
`on_solaris` ✅ 
`debian-clang-devel` ✅ 
`debian-gcc-devel` ✅ 
`fedora-clang-devel` ✅ 
`macos-highsierra-release-cran` ✅ 
`check_for_cran` ✅

**Comment by ALanguillaume** [comment]
This will close https://github.com/ThinkR-open/gitlabr/issues/97
