### ISSUE TITLE
As dev, I want to know the steps to contribute to the development of {gitlabr} 

### ISSUE THREAD

**Issue by MurielleDelmotte** [ThinkR-open/gitlabr#103]
If I follow the steps in the CONTRIBUTING.md/create_testor_on_gitlab.R file, I can't run `devtools::test()`

## Validation

- [ ] We don't close the connection to gitlab until all the repo are created
- [ ] We have the complete list of projects needed to run `devtools::test()`

## Technical

In `create_testor_on_gitlab.R`:

Move at the end of file:
```
  # Unset connection
  unset_gitlab_connection()
```

*All* packages are required to run `devtools::test()` (CI **AND** Local): 

```
# CI only - to allow run in parallel
projects_names <- c("testor.macos", "testor.windows", "testor.release",
                    "testor.devel", "testor.release.master", "testor.coverage")
# Local - Only the first one is mandatory
projects_names <- c("testor.main", "testor.master")
```

**Comment by statnmap** [comment]
CONTRIBUTING was modified to allow the preparation of a unique test repository.  Unit tests as well.
All other repos are used for the CI only.  

See : https://github.com/ThinkR-open/gitlabr/blob/main/CONTRIBUTING.md
