### ISSUE TITLE
Verify {tibble} version because of "name.repair"

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/gitlabr#8]
I corrected the code with a `name.repair` to avoid problems with {tibble} 4.0.  
There is a need to verify if the modification has some problems with earlier versions of {tibble} or if we need to specify >4.0 in the DESCRIPTION.

**Comment by LDalby** [comment]
As far as I can see, {tibble} is currently on version 3.0.3 - do you mean version 3.0 and not 4.0?

**Comment by statnmap** [comment]
Yes sure. I was a little bit early...

**Comment by LDalby** [comment]
Tried to install {gitlabr} on a fresh server just now. 
With {tibble} 1.4.2 I get this on loading {gitlabr}: 

```Error: package or namespace load failed for ‘gitlabr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): namespace ‘tibble’ 1.4.2 is already loaded, but >= 2.1.3 is required```

after upgrading to {tibble} 2.1.3 I get no error when loading {gitlabr}. The DESCRIPTION for {gitlabr} actually says {tibble} > 1.1 so I guess the {tibble} 2.1.3 requirement comes for one of the other dependencies. 

Does this solve the issue here or was there a specific function you'd like to have tested?

**Comment by statnmap** [comment]
Not really. The problem stands there:
https://github.com/statnmap/gitlabr/blob/347faf31cc113820b70e03563a4b925975646c40/R/gitlab_api.R#L190

The output of the `lapply()` get some columns with the same name which is not allowed anymore in `tibble()`. I thus had to use the `name.repair` parameter as a quick modification. However, I did not verify if this modification has any repercution on other outputs. I am not sure where these duplicated columns are used. (Don't even remember which ones these were...)  
Maybe this is one of the reasons why some unit tests fail when comparing different methods like here: https://github.com/statnmap/gitlabr/issues/14.

A way to explore this, would probably be to change the name.repair method and see if this has some repercutions in the unit tests. A new set of specific unit tests could help too...

**Comment by LDalby** [comment]
Right, I see. I actually tried to search for `name_repair` on my fork of this repo, but nothing showed up. Not sure why it only shows up under your version of the repo 🤔
