### ISSUE TITLE
{gitlabr} migration to ThinkR-open

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/gitlabr#97]
## Validation

- [x] {gitlabr} is clearly stated has being maintained on ThinkR-Open on the CRAN page

## Technicals

- [x] Migrate to ThinkR-open
- [x] Change links in Description for issues
- [x] Verify secrets
- [x] Add template ThinkR for {pkgdown}
- [x] Modify list for r-universe
- [ ] Make a release on CRAN

**Comment by ALanguillaume** [comment]
The only thing missing here is a new release to CRAN so that DESCRIPTION on CRAN is updated with the new url pointing to thinkr-open and not statnmap account.

**Comment by statnmap** [comment]
Release on CRAN is coming soon. I think we can close this issue now.
